feat/chrome-extension-hello-world
evmts/onchain-clippy pull request #6
Opened 2024-12-17 17:33 UTC by g4titanx

completing task:
- [ ]  Add a hello world chrome extension with docs on how to set up dev env to use it in CONTRIBUTING.md (200 AI16z)

sol add: BjQWDZuX8o4BGi2dip9sgR5CnQ6XwCXoYPNFTSHxfdBT

2024-12-17 18:26 UTC, g4titanx commented
@roninjin10

2024-12-18 06:33 UTC, roninjin10 commented
Can you rebase? Make sure to remove all the stuff that git ignore should be removing like node modules

2024-12-18 08:03 UTC, g4titanx commented
> Can you rebase? Make sure to remove all the stuff that git ignore should be removing like node modules

done

2024-12-18 08:50 UTC, roninjin10 commented on app/extension/tsconfig.json
> +  "include": ["src"]
Let's keep the stricter old settings

2024-12-18 08:51 UTC, roninjin10 commented on app/extension/tsconfig.json
> +  "include": ["src"]
We will need to install that @tevm/tsconfig package

2024-12-18 08:51 UTC, roninjin10 commented on app/extension/package.json
> +    "@types/chrome": "^0.0.260",
will need to add @tevm/tsconfig as dep here

2024-12-18 08:52 UTC, roninjin10 requested changes
Small fixes from previous prs

2024-12-18 09:14 UTC, g4titanx commented
done @roninjin10

2024-12-18 10:33 UTC, roninjin10 approved these changes

2024-12-18 10:33 UTC, roninjin10 commented
Thank you will send Christmas gift

2024-12-18 10:33 UTC, merged